# Generated by Django 5.1.1 on 2024-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_variant', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('number_of_doors', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('engine_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gearbox', models.CharField(max_length=50)),
            ],
        ),
    ]
