# Generated by Django 5.1.1 on 2024-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='gearbox',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='', upload_to='car_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model_variant',
            field=models.CharField(max_length=100),
        ),
    ]
