# Generated by Django 5.1.1 on 2024-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3500, max_digits=10),
            preserve_default=False,
        ),
    ]
