# Generated by Django 5.1.1 on 2024-10-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_car_user_car_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
