# Generated by Django 5.1.1 on 2024-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_car_number_of_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
