# Generated by Django 5.1.1 on 2024-10-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_userpreference_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
