# Generated by Django 5.1.1 on 2024-11-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
