# Generated by Django 5.1.1 on 2025-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_profile_user_delete_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
