# Generated by Django 5.1.3 on 2025-03-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='car',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
